ROBOT       = wolfo01
SHIPDIR     = drivers/${ROBOT}/1
SHIP        =  car5-trb1.rgb  default.xml
SHIPSUBDIRS = practice qualifying race

PKGSUBDIRS  = ${SHIPSUBDIRS}
src-robots-wolfo01_PKGFILES = $(shell find * -maxdepth 0 -type f -print)
src-robots-wolfo01_PKGDIR   = ${PACKAGE}-${VERSION}/$(subst ${TORCS_BASE},,$(shell pwd))
include ${MAKE_DEFAULT}