#!/usr/bin/perl -w

print "Usage: mk-test <freq>" unless @ARGV;

$rate= 256;
$freq= (shift) / $rate;
$PI= 2 * atan2(1,0);

die unless open OUT, ">test.dat";

for (0..65535) {
    my $val= int(32766 * sin($_ * $freq * $PI * 2));
    print OUT pack("s", $val);
}
